spring:
  application:
    name: cine-backend-reactive
  r2dbc:
    url: r2dbc:h2:mem:///cinemas;DB_CLOSE_DELAY=-1
  flyway:
    url: jdbc:h2:mem:cinemas;DB_CLOSE_DELAY=-1
    locations: classpath:db/h2/migration
credentials:
  key-movies: 9e160a8c


