spring:
  application:
    name: cine-backend-reactive
  r2dbc:
    url: r2dbc:h2:mem:///employees;DB_CLOSE_DELAY=-1
    username: sa
    password:
  flyway:
    url: jdbc:h2:mem:employees;DB_CLOSE_DELAY=-1
    locations: classpath:db/h2/migration

